Repository haproxytech/haproxy-consul-connect, pull requests merged in 2020-04, with the labels that each got.

#21 [BUGFIX] Properly detect failure to launch process
  haproxy/haproxy_cmd/cmd.go
  haproxy/haproxy_cmd/cmd_test.go
  haproxy/haproxy_cmd/run.go
Labels: bug, criteo

#22 When test went wrong, test was not stopping properly.
  haproxy/config.go
  haproxy_test.go
  utils_test.go
Labels: criteo

#23 Added CHANGELOG.md
  CHANGELOG.md
Labels: criteo

#24 Added Version information in the build
  .travis.yml
  GNUmakefile
  main.go
Labels: criteo, enhancement

#25 Removed wrongly added debug message
  haproxy/haproxy_cmd/run.go
Labels: bug, criteo

#20 Updated readme with full usage
  README.md
Labels: criteo

#26 REFACTOR Updated references to go mod github.com/haproxytech/haproxy-consul-connect
  README.md
  consul/logger.go
  go.mod
  haproxy/certs.go
  haproxy/config.go
  haproxy/haproxy.go
  haproxy/haproxy_cmd/cmd.go
  haproxy/haproxy_cmd/cmd_test.go
  haproxy/haproxy_cmd/run.go
  haproxy/spoe.go
  haproxy/state.go
  haproxy/state/downstream.go
  haproxy/state/from_ha.go
  haproxy/state/from_ha_test.go
  haproxy/state/snapshot_test.go
  haproxy/state/states.go
  haproxy/state/upstream.go
  haproxy/stats.go
  haproxy_test.go
  main.go
  utils_test.go
Labels: criteo

#30 BUGFIX Fix unstable unit test TestFromHA
  haproxy/state/from_ha_test.go
  haproxy/state/state.go
Labels: criteo

#31 FEATURE Check dataplaneapi and haproxy binaries
  haproxy/haproxy.go
  haproxy/haproxy_cmd/run.go
  haproxy/state/from_ha_test.go
  main.go
Labels: criteo

#33 BUILD: ensure GNUMakefile is used, so unit tests are run
  .travis.yml
  haproxy_test.go
Labels: criteo

#29 REGTEST Added unit test for shutdown
  lib/shutdown.go
  lib/shutdown_test.go
Labels: criteo

#35 REGTEST Added unit tests for logs
  haproxy/halog/log_test.go
Labels: criteo

#37 BUG fix double execution of processes
  haproxy/haproxy_cmd/run.go
Labels: criteo

#36 BUILD/MEDIUM: add haproxy and dataplane binaries to travis
  .travis.yml
Labels: haproxy

#28 BUILD Update Consul APIs to 1.4.0 and Consul to 1.7.2
  consul/watcher.go
  go.mod
  go.sum
Labels: criteo

#16 MEDIUM: Add support for "mode tcp"
  consul/config.go
  consul/watcher.go
  haproxy/state/downstream.go
  haproxy/state/upstream.go
Labels: enhancement, haproxy

#40 Add enable_forwardfor option
  consul/config.go
  consul/watcher.go
  haproxy/state/downstream.go
  haproxy/state/utils.go
Labels: criteo
